### ISSUE TITLE
Feature Request: English & Windows x64 support

### ISSUE THREAD

**Issue by Mirrorman95** [blueur/the-stanly-parable#1]
Hello, I am a fan of The Stanley Parable, and I'm currently playing your game on my computer offline. Which was a little difficult to accomplish, because I had to download the source code, unpack it, and copy parts of another RenPy 8.10 game into it to make it run on my Windows x64 computer. (Which made it confusing to see that error screen in the intro that said RenPy 8.0.3 until I realized it was a pre-rendered joke.) But that was the easy part.

The hard part is that the game is only available in French, which I assume is your native language. Now I know some French, but not fluently enough to translate it in real-time. So I've been running parts of the rpy scripts into Google Translate a piece at at time to understand the game text. And even then, it didn't work on certain words like COU###ES and I had to do some serious digging to figure out that it means BALLS. Now your game is pretty funny, but it would be funnier and easier to play, at least for me, if these features were available as an integrated part of the game. I also realize that this game has not been officially released by you and that as such, a lack of functionality is to be expected. But I felt it couldn't hurt to ask about implementing these features in the future.

**Comment by blueur** [comment]
Hi,
I'm glad that you like the game, but the development will unfortunately not be continued.
Best,
